services:
  mysql:
    image: mysql:8.4
    container_name: day02-mysql
    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: lab

    ports:
      - "3308:3306"

    volumes:
      - day02-mysql-data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d:ro

    healthcheck:
      test: ["CMD-SHELL", 'mysqladmin ping -h 127.0.0.1 -uroot -p"$$MYSQL_ROOT_PASSWORD" --silent']
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

volumes:
  day02-mysql-data:
    name: day02-mysql-data